runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  OPENAI_API_KEY: ""  # Will be set through GCP Secret Manager
  GOOGLE_AI_API_KEY: ""  # Will be set through GCP Secret Manager
  GOOGLE_CLOUD_PROJECT: "finance-data-pipeline"

service_account: finance-data-pipeline@appspot.gserviceaccount.com

handlers:
  - url: /.*
    script: auto 