financial_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: tr28614.us-east4.gcp
      user: dev_dhrumil_user
      password: Dhrumil@123
      role: ACCOUNTADMIN
      database: ASSIGNMENT2_TEAM1
      warehouse: COMPUTE_WH
      schema: FACT_TABLE_STAGING
      threads: 4
